import { strict as assert } from "node:assert";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const assetPath = new URL(
  "../apps/web/public/assets/intent-path-texture.png",
  import.meta.url
);
const flowPath = new URL(
  "../apps/web/components/intent-flow.tsx",
  import.meta.url
);
const ogPath = new URL(
  "../apps/web/components/site-opengraph.tsx",
  import.meta.url
);

test("Image 2 auxiliary asset is a real PNG with no textual payload", async () => {
  const asset = await readFile(assetPath);
  assert.deepEqual([...asset.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10]);

  const flowSource = await readFile(flowPath, "utf8");
  assert.match(flowSource, /intent-path-texture\.png/);
  assert.match(flowSource, /alt=\"\"/);
  assert.match(flowSource, /aria-label=\{step\.label\}/);
});

test("intent flow keeps the four labels and familiar icon set in code", async () => {
  const flowSource = await readFile(flowPath, "utf8");
  for (const label of [
    "Find a university",
    "Choose your role",
    "See the rules",
    "Open official source"
  ]) {
    assert.match(flowSource, new RegExp(label));
  }
  for (const icon of ["search", "person", "check", "source"]) {
    assert.match(flowSource, new RegExp(`\"${icon}\"`));
  }
});

test("OG image text is generated by the programmatic card", async () => {
  const ogSource = await readFile(ogPath, "utf8");
  assert.match(ogSource, /new ImageResponse/);
  assert.match(ogSource, /From a university question to the official source/);
  assert.doesNotMatch(ogSource, /university logo|seal|wordmark/i);
});
