import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";

type Json = Record<string, any>;
const generatedAt = new Date().toISOString();
const extensionRunId = "uapt-ai-tools-qs-601-700-20260719-011";
const topRunId = "uapt-ai-tools-qs-top-700-20260719-011";
const releaseId = "public-release-20260719-011";
const baselinePath = "staging/ai-tools/release-candidates/uapt-ai-tools-qs-top-600-20260718-009/tool_records.json";
const baselineBundlePath = "staging/uapt-runs/uapt-ai-tools-qs-top-600-20260718-009/artifacts.json";
const discoveryPath = "staging/ai-tools/audits/qs-601-700-discovery-20260719-011.json";
const confirmedPath = "staging/ai-tools/audits/qs-601-700-confirmed-records-20260719-011.json";
const extRoot = `staging/ai-tools/release-candidates/${extensionRunId}`;
const topRoot = `staging/ai-tools/release-candidates/${topRunId}`;
const runRoot = `staging/uapt-runs/${topRunId}`;
const id = (record: Json) => `${record.universitySlug}:${record.tool}:${record.rawToolName}`;

async function main() {
  const [ranking, discovery, confirmed, baselineText, baselineBundle, current] = await Promise.all([
    json("data/rankings/qs-world-university-rankings-2026-top-1000.json"), json(discoveryPath), json(confirmedPath), readFile(baselinePath,"utf8"), json(baselineBundlePath), currentBase()
  ]);
  if (current.releaseId !== "public-release-20260718-009") throw new Error(`Expected production 009, got ${current.releaseId}`);
  const baseline = JSON.parse(baselineText); const records = confirmed.records as Json[];
  const rows = ranking.universities.filter((row:Json)=>row.rowNumber>=601&&row.rowNumber<=700);
  if(rows.length!==100||discovery.rows.length!==100)throw new Error("QS 601-700 cohort must contain exactly 100 source rows");
  const byRow=new Map<number,Json[]>();for(const record of records)byRow.set(record.qsRow,[...(byRow.get(record.qsRow)??[]),record]);
  const discoveryByRow=new Map(discovery.rows.map((row:Json)=>[row.qsRow,row]));
  const recordKeys=records.map(id);if(new Set(recordKeys).size!==records.length)throw new Error("Duplicate extension record IDs");
  const selectedByUrl=new Map<string,Json[]>();for(const record of records)for(const evidence of record.evidence??[]){const key=canonical(evidence.sourceUrl);selectedByUrl.set(key,[...(selectedByUrl.get(key)??[]),record]);}

  const reviewDecisions:Json[]=[];
  const ledgerEntries=rows.map((rankingRow:Json)=>{
    const row=discoveryByRow.get(rankingRow.rowNumber);if(!row)throw new Error(`Missing discovery row ${rankingRow.rowNumber}`);
    const rowRecords=byRow.get(rankingRow.rowNumber)??[];const candidatePages=(row.pages??[]).filter((page:Json)=>page.fetchStatus==="ok"&&((page.semanticSignals?.productTerms?.length??0)>0)&&((page.semanticSignals?.accessTerms?.length??0)>0));
    const decisionUrls=new Set<string>();
    for(const page of candidatePages){const key=canonical(page.finalUrl);decisionUrls.add(key);const matched=(selectedByUrl.get(key)??[]).filter(record=>record.qsRow===rankingRow.rowNumber);reviewDecisions.push(decision(rankingRow,row,page,matched));}
    for(const record of rowRecords)for(const evidence of record.evidence??[]){const key=canonical(evidence.sourceUrl);if(decisionUrls.has(key))continue;decisionUrls.add(key);reviewDecisions.push(decision(rankingRow,row,{finalUrl:evidence.sourceUrl,snapshotPath:evidence.snapshotPath,snapshotHash:evidence.snapshotHash,provider:"direct_official_evidence_review",semanticSignals:{productTerms:[record.rawToolName],accessTerms:["institutional access"]}},rowRecords.filter(value=>(value.evidence??[]).some((item:Json)=>canonical(item.sourceUrl)===key))));}
    const searches=row.searches??[];const errors=searches.filter((search:Json)=>search.status==="error");const sourceUrls=[...new Set(rowRecords.flatMap((record:Json)=>(record.evidence??[]).map((evidence:Json)=>evidence.sourceUrl)))];
    return {qsRow:rankingRow.rowNumber,qsRank:rankingRow.rankNumber,universityName:rankingRow.name,countryOrRegion:rankingRow.countryOrRegion,officialDomain:row.officialDomain,localLanguage:row.localLanguage,requiredSearchMatrix:searches.map((search:Json)=>({matrixId:search.matrixId,language:search.language,query:search.query})),auditStatus:rowRecords.length?"audited_positive":"blocked",verifiedZero:false,blockingReason:rowRecords.length?null:"No product-level institutional-access record was verified from the successfully reviewed official material. Search/fetch incompleteness is preserved, so this is blocked/null rather than a verified zero.",searchTrace:searches,searchBoundary:{successfulOrEmpty:searches.length-errors.length,errors:errors.length,errorQueries:errors.map((search:Json)=>({matrixId:search.matrixId,query:search.query,attempt:search.attempt,error:search.error}))},directOfficialPageChecks:row.pages??[],recordIds:rowRecords.map(id),approvedToolsSources:sourceUrls.map(sourceUrl=>({sourceUrl,official:true,recordIds:rowRecords.filter((record:Json)=>(record.evidence??[]).some((evidence:Json)=>evidence.sourceUrl===sourceUrl)).map(id)}))};
  });
  const searchCount=discovery.rows.flatMap((row:Json)=>row.searches??[]).length;const searchErrors=discovery.rows.flatMap((row:Json)=>row.searches??[]).filter((search:Json)=>search.status==="error").length;const pageCount=discovery.rows.flatMap((row:Json)=>row.pages??[]).length;
  const ledger={schemaVersion:"uapt-ai-tools-audit-ledger-v1",runId:extensionRunId,generatedAt,scope:{selection:"QS 2026 exact source rows 601-700",sourceRanking:"data/rankings/qs-world-university-rankings-2026-top-1000.json",rows:[601,700],policy:"No blocked row is asserted to be a zero."},summary:{rows:100,positiveRows:byRow.size,records:records.length,blockedRows:100-byRow.size,verifiedZero:0,searchTraces:searchCount,searchErrors,directOfficialChecks:pageCount,localLanguageRows:discovery.rows.filter((row:Json)=>row.localLanguage!=="en").length,undLocalLanguageRows:discovery.rows.filter((row:Json)=>!row.localLanguage||row.localLanguage==="und").length},entries:ledgerEntries};
  const review={schemaVersion:"uapt-ai-tools-high-risk-semantic-review-v1",runId:extensionRunId,generatedAt,policy:"Every official page carrying both product and institutional-access signals, plus every selected evidence source, receives an explicit semantic decision. Heuristics never create records.",summary:{reviewed:reviewDecisions.length,positiveSources:reviewDecisions.filter(item=>item.semanticDecision==="positive_records_added").length,excludedSources:reviewDecisions.filter(item=>item.semanticDecision==="excluded_after_review").length,records:records.length},decisions:reviewDecisions};
  const extension={...confirmed,runId:extensionRunId,generatedAt};const topRecords=[...baseline.records,...records];const topKeys=topRecords.map(id);if(new Set(topKeys).size!==topRecords.length)throw new Error("Top-700 duplicate record ID");
  const top={schemaVersion:"uapt-ai-tools-records-v1",runId:topRunId,generatedAt,reviewState:"agent_reviewed",records:topRecords};
  const baselineHash=sha(baselineText);const extText=stringify(extension);const topText=stringify(top);
  const candidateManifest={schemaVersion:"uapt-ai-tools-candidate-manifest-v1",candidateOnly:true,runId:topRunId,generatedAt,baseline:{path:baselinePath,runId:baseline.runId,sha256:baselineHash,records:baseline.records.length,immutable:true},extension:{path:`${extRoot}/tool_records.json`,runId:extensionRunId,records:records.length,universities:byRow.size,sources:new Set(records.flatMap((record:Json)=>record.evidence.map((evidence:Json)=>evidence.sourceUrl))).size},output:{path:`${topRoot}/tool_records.json`,records:topRecords.length,sha256:sha(topText)},ledger:{path:"staging/ai-tools/audits/qs-601-700-ai-tools-audit-ledger-20260719-011.json",rows:100},semanticReview:{path:"staging/ai-tools/audits/qs-601-700-high-risk-semantic-review-20260719-011.json",reviewed:reviewDecisions.length}};
  const bundle=seedBundle(baselineBundle,records,topRunId);
  const publicCandidate=structuredClone(current);publicCandidate.releaseId=releaseId;publicCandidate.publishedAt=generatedAt;publicCandidate.description="QS top-700 AI tools 011 release: repairs and fully re-audits exact QS source rows 601-700 while preserving the immutable 009 Top-600 production baseline.";publicCandidate.candidateOnly=true;publicCandidate.previousReleaseId=current.releaseId;publicCandidate.includeStagedArtifactDirectories=[...new Set([...(current.includeStagedArtifactDirectories??[]),runRoot])];publicCandidate.notes=[`Publishes ${topRecords.length} official-source AI tool records for ${new Set(topRecords.map((record:Json)=>record.universitySlug)).size} universities from ${new Set(topRecords.flatMap((record:Json)=>record.evidence.map((evidence:Json)=>evidence.sourceUrl))).size} official sources.`,`The QS rows 601-700 extension contains ${records.length} records across ${byRow.size} universities from ${new Set(records.flatMap((record:Json)=>record.evidence.map((evidence:Json)=>evidence.sourceUrl))).size} official sources.`,`All 100 exact source rows were re-audited with ${searchCount} multilingual query traces; ${searchErrors} Firecrawl failures remain explicit search boundaries and no blocked row is asserted as a verified zero.`,`All ${reviewDecisions.length} semantic candidate/evidence surfaces have explicit source-level decisions.`,`The immutable Top-600 009 baseline is preserved byte-for-byte at SHA-256 ${baselineHash}.`,"Promotion requires independent QA, release validation, public-data audit, full pnpm check, production build, and live API verification.","Tracker metadata is open licensed; official source documents retain their original rights."];
  await Promise.all([mkdir(extRoot,{recursive:true}),mkdir(topRoot,{recursive:true}),mkdir(runRoot,{recursive:true}),mkdir("data/public-releases/candidates",{recursive:true})]);
  await Promise.all([writeFile(`${extRoot}/tool_records.json`,extText),writeFile(`${topRoot}/tool_records.json`,topText),writeFile(`${topRoot}/candidate-manifest.json`,stringify(candidateManifest)),writeFile("staging/ai-tools/audits/qs-601-700-ai-tools-audit-ledger-20260719-011.json",stringify(ledger)),writeFile("staging/ai-tools/audits/qs-601-700-high-risk-semantic-review-20260719-011.json",stringify(review)),writeFile(`${runRoot}/artifacts.json`,stringify(bundle)),writeFile(`data/public-releases/candidates/${releaseId}.json`,stringify(publicCandidate))]);
  const rebuilt = spawnSync("pnpm", ["exec", "tsx", "scripts/rebuild-ai-tools-openclaw-artifacts.ts", `${topRoot}/tool_records.json`, `${runRoot}/artifacts.json`], { stdio: "inherit" });
  if (rebuilt.status !== 0) throw new Error("Failed to rebuild the complete Top-700 OpenClaw artifact bundle");
  console.log(JSON.stringify({extensionRecords:records.length,extensionUniversities:byRow.size,topRecords:topRecords.length,reviewedSurfaces:reviewDecisions.length,searchCount,searchErrors,baselineHash},null,2));
}

function decision(rankingRow:Json,row:Json,page:Json,matched:Json[]){return {qsRow:rankingRow.rowNumber,qsRank:rankingRow.rankNumber,universityName:rankingRow.name,officialDomain:row.officialDomain,sourceUrl:page.finalUrl,snapshotPath:page.snapshotPath??null,snapshotHash:page.snapshotHash??null,provider:page.provider,productSignals:page.semanticSignals?.productTerms??[],accessSignals:page.semanticSignals?.accessTerms??[],semanticDecision:matched.length?"positive_records_added":"excluded_after_review",rationale:matched.length?"Official source establishes a current university licence, provision, supported account path, procurement route, or institution-operated service.":"The page was reviewed but did not establish a distinct current product-level institutional entitlement beyond generic guidance, research, teaching material, expired/trial access, vendor content, or a duplicate selected source.",recordIds:matched.map(id),reviewerOrigin:"qs-601-700-20260719-011-source-level-semantic-review",reviewedAt:generatedAt};}
function seedBundle(base:Json,records:Json[],runId:string){const bundle=structuredClone(base);bundle.runId=runId;for(const artifact of bundle.artifacts)artifact.runId=runId;const artifacts=bundle.artifacts as Json[];const sources=new Map<string,{record:Json,evidence:Json}>();for(const record of records)for(const evidence of record.evidence??[])if(!sources.has(`${record.universitySlug}\0${evidence.sourceUrl}`))sources.set(`${record.universitySlug}\0${evidence.sourceUrl}`,{record,evidence});const plan=artifacts.find(item=>item.artifactType==="crawl_plan");const trace=artifacts.find(item=>item.artifactType==="source_discovery_trace");for(const {record,evidence} of sources.values()){const sourceCandidateId=`sc-${sha(`${record.universitySlug}:${evidence.sourceUrl}`).slice(0,16)}`;plan.targets.push({entityType:"university",entitySlug:record.universitySlug,sourceCandidateId,sourceUrl:evidence.sourceUrl,sourceTitle:evidence.sourceTitle,sourceLanguage:evidence.sourceLanguage??"und",allowedFetchModes:["http","firecrawl"],expectedThemes:["approved_tools"],maxUrls:1,robotsPolicy:"respect"});trace.candidateIds.push(sourceCandidateId);artifacts.push({schemaVersion:"openclaw-artifact-v1",runId,artifactType:"source_candidate",sourceCandidateId,entityType:"university",entitySlug:record.universitySlug,sourceUrl:evidence.sourceUrl,finalUrl:evidence.sourceUrl,sourceTitle:evidence.sourceTitle,sourceLanguage:evidence.sourceLanguage??"und",sourceType:"approved_tools",discoveryMethod:"public_web_search",queryUsed:"QS rows 601-700 multilingual official-domain AI tools audit",discoveredAt:evidence.sourceFetchedAt,officialDomainConfidence:1,aiRelevanceScore:.99,policySpecificityScore:.98,verificationStatus:"verified",verifiedAt:generatedAt,verificationNotes:"Official source product-level institutional-access evidence reviewed and snapshotted.",robotsPolicy:"respect"});artifacts.push({schemaVersion:"openclaw-artifact-v1",runId,artifactType:"fetch_attempt",fetchAttemptId:`fa-${sourceCandidateId}`,sourceCandidateId,sourceUrl:evidence.sourceUrl,finalUrl:evidence.sourceUrl,attemptedAt:evidence.sourceFetchedAt,fetchMode:"http",userAgentKind:"browser_like",httpStatus:200,contentType:evidence.sourceUrl.toLowerCase().includes(".pdf")?"application/pdf":"text/html",robotsAllowed:true,outcome:"success",contentHash:evidence.snapshotHash,normalizedTextStorageKey:evidence.snapshotPath});}trace.methodsAttempted.push({method:"public_web_search",query:"QS exact source rows 601-700 multilingual official-domain institutional AI access",resultCount:sources.size,notes:"1108 query traces and all semantic decisions are retained in the 011 audit files."});const report=artifacts.find(item=>item.artifactType==="report_draft");report.title="QS top-700 AI tools 011 release";report.summary=`Top-700 candidate extends immutable 009 with ${records.length} reviewed records from exact QS rows 601-700.`;return bundle;}
function canonical(value:string){try{const url=new URL(value);url.hash="";return `${url.hostname.toLowerCase().replace(/^www\./,"")}${url.pathname.replace(/\/$/,"")}${url.search}`;}catch{return value;}}
function sha(value:string|Buffer){return createHash("sha256").update(value).digest("hex");}
function stringify(value:unknown){return `${JSON.stringify(value,null,2)}\n`;}
async function json(file:string):Promise<Json>{return JSON.parse(await readFile(file,"utf8"));}
async function currentBase():Promise<Json>{const current=await json("data/public-releases/current.json");return current.releaseId===releaseId?json("data/public-releases/history/public-release-20260718-009.json"):current;}
void main().catch(error=>{console.error(error);process.exitCode=1;});
