import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

type Json = Record<string, any>;
type Row = { rowNumber: number; rankNumber: number; name: string; countryOrRegion: string };
const RUN = "uapt-ai-tools-qs-501-600-20260718-009";
const OUTPUT = "staging/ai-tools/audits/qs-501-600-search-traces-20260718-009.json";
const MATRIX: Array<[string, string]> = [
  ["official_home_it_directory", "official IT digital services service catalogue AI"],
  ["approved_authorized_recommended", "approved authorized recommended AI tools"],
  ["institutional_licence_procurement", "institutional licence procurement enterprise AI access"],
  ["product_terms", "ChatGPT Copilot Gemini NotebookLM Claude Perplexity"],
  ["university_platform_self_hosted", "university AI platform self-hosted chatbot"],
  ["library_teaching_research_procurement", "library teaching research office procurement generative AI"],
  ["campus_licences", "Microsoft 365 Google Workspace Adobe GitHub campus licence"],
  ["local_access_synonyms", "AI university account campus access free institutional service"]
];
const LOCAL: Record<string, [string, string, string]> = {
  "United Arab Emirates": ["ar", "الذكاء الاصطناعي ترخيص شراء حساب الجامعة وصول", "AE"], Belgium: ["nl", "kunstmatige intelligentie licentie universiteitsaccount toegang", "BE"], Taiwan: ["zh", "人工智慧 生成式AI 授權 採購 學校帳號", "TW"], Hungary: ["hu", "mesterséges intelligencia licenc egyetemi fiók hozzáférés", "HU"], Italy: ["it", "intelligenza artificiale licenza account universitario accesso", "IT"], Russia: ["ru", "искусственный интеллект лицензия университетский аккаунт доступ", "RU"], Malaysia: ["ms", "kecerdasan buatan lesen akaun universiti akses", "MY"], Chile: ["es", "inteligencia artificial licencia cuenta universitaria acceso", "CL"], Germany: ["de", "künstliche Intelligenz Lizenz Universitätskonto Zugang", "DE"], "South Korea": ["ko", "인공지능 생성형 AI 라이선스 대학 계정 접근", "KR"], Lebanon: ["ar", "الذكاء الاصطناعي ترخيص حساب الجامعة وصول", "LB"], "China (Mainland)": ["zh", "人工智能 生成式AI 采购 授权 校园账号", "CN"], "Saudi Arabia": ["ar", "الذكاء الاصطناعي ترخيص شراء حساب الجامعة وصول", "SA"], Indonesia: ["id", "kecerdasan buatan lisensi akun universitas akses", "ID"], Spain: ["es", "inteligencia artificial licencia cuenta universitaria acceso", "ES"], Türkiye: ["tr", "yapay zeka lisans üniversite hesabı erişim", "TR"], Greece: ["el", "τεχνητή νοημοσύνη άδεια πανεπιστημιακός λογαριασμός πρόσβαση", "GR"], Estonia: ["et", "tehisintellekt litsents ülikooli konto juurdepääs", "EE"], Czechia: ["cs", "umělá inteligence licence univerzitní účet přístup", "CZ"], Switzerland: ["fr", "intelligence artificielle licence compte universitaire accès", "CH"], Finland: ["fi", "tekoäly lisenssi yliopistotunnus pääsy", "FI"], Norway: ["no", "kunstig intelligens lisens universitetskonto tilgang", "NO"], Austria: ["de", "künstliche Intelligenz Lizenz Universitätskonto Zugang", "AT"], Uruguay: ["es", "inteligencia artificial licencia cuenta universitaria acceso", "UY"], Philippines: ["en", "AI institutional licence university account access", "PH"], Pakistan: ["ur", "مصنوعی ذہانت لائسنس یونیورسٹی اکاؤنٹ رسائی", "PK"], Israel: ["he", "בינה מלאכותית רישיון חשבון אוניברסיטה גישה", "IL"], France: ["fr", "intelligence artificielle licence compte universitaire accès", "FR"], India: ["hi", "कृत्रिम बुद्धिमत्ता लाइसेंस विश्वविद्यालय खाता पहुंच", "IN"], Slovakia: ["sk", "umelá inteligencia licencia univerzitný účet prístup", "SK"], Vietnam: ["vi", "trí tuệ nhân tạo giấy phép tài khoản đại học truy cập", "VN"], Cyprus: ["el", "τεχνητή νοημοσύνη άδεια πανεπιστημιακός λογαριασμός πρόσβαση", "CY"], Ukraine: ["uk", "штучний інтелект ліцензія університетський обліковий запис доступ", "UA"], Bulgaria: ["bg", "изкуствен интелект лиценз университетски акаунт достъп", "BG"], Venezuela: ["es", "inteligencia artificial licencia cuenta universitaria acceso", "VE"]
};
const EN = new Set(["United States", "United Kingdom", "Canada", "Australia"]);
void main().catch((error) => { console.error(error); process.exitCode = 1; });
async function main() {
  const key = await keyFromConfig(); const ranking = await json("data/rankings/qs-world-university-rankings-2026-top-1000.json"); const rows: Row[] = ranking.universities.filter((r: Row) => r.rowNumber >= 501 && r.rowNumber <= 600).sort((a: Row,b: Row) => a.rowNumber-b.rowNumber);
  if (rows.length !== 100) throw new Error(`Expected 100 QS source rows, found ${rows.length}`);
  const domains = await domainsFromHistoricBundles(); const out: Json[] = [];
  for (let start = 0; start < rows.length; start += 8) {
    const batch = await Promise.all(rows.slice(start,start+8).map((row) => auditRow(row, domains.get(slug(row.name)), key)));
    out.push(...batch); out.sort((a,b) => a.qsRow-b.qsRow); await persist(out); console.log(`Saved rows ${out.length}/100`);
  }
}
async function auditRow(row: Row, domain: string | undefined, key: string) {
  const local = LOCAL[row.countryOrRegion] ?? [EN.has(row.countryOrRegion) ? "en" : "und", "AI licence university account access", "US"]; const traces: Json[]=[];
  for (const [matrixId, terms] of MATRIX) { traces.push({matrixId,...await search(key, `"${row.name}" ${terms}${domain ? ` site:${domain}` : ""}`, "en", domain, local[2])}); if (local[0]!=="en" && local[0]!=="und") traces.push({matrixId,...await search(key, `"${row.name}" ${matrixId==="local_access_synonyms"?local[1]:`${terms} ${local[1]}`}${domain ? ` site:${domain}` : ""}`, local[0], domain, local[2])}); }
  return {qsRow:row.rowNumber,qsRank:row.rankNumber,universityName:row.name,countryOrRegion:row.countryOrRegion,localUniversityName:row.name,localLanguage:local[0],officialDomain:domain??null,requiredSearchMatrix:MATRIX.map(([id])=>id),searchTrace:traces};
}
async function search(key:string,query:string,queryLanguage:string,domain:string|undefined,country:string){const searchedAt=new Date().toISOString();try{const response=await fetch("https://api.firecrawl.dev/v2/search",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({query,limit:8,sources:["web"],country,timeout:30000})});const data=await response.json();const results=data?.data?.web??data?.data??[];const candidateUrls=[...new Set(results.map((x:Json)=>x.url).filter((url:unknown):url is string=>typeof url==="string"&&official(url,domain)))];return {query,queryLanguage,provider:"firecrawl_search_v2",searchedAt,firecrawlSearchId:data?.id??null,creditsUsed:data?.creditsUsed??null,fetchStatus:response.ok?(candidateUrls.length?"ok":"empty"):"error",candidateUrls,filteredIrrelevantCount:results.length-candidateUrls.length,filteringConclusion:candidateUrls.length?"Official-domain candidate URLs retained for direct review.":response.ok?"HTTP 200 with no official-domain candidate URL; recorded as empty.":`Firecrawl HTTP ${response.status}`,...(response.ok?{}:{error:String(data?.error??`HTTP ${response.status}`)})};}catch(error){return{query,queryLanguage,provider:"firecrawl_search_v2",searchedAt,fetchStatus:"error",candidateUrls:[],filteredIrrelevantCount:0,filteringConclusion:"Firecrawl search failed.",error:String(error)}}}
async function domainsFromHistoricBundles(){const wanted=new Set((await json("data/rankings/qs-world-university-rankings-2026-top-1000.json")).universities.filter((r:Row)=>r.rowNumber>=501&&r.rowNumber<=600).map((r:Row)=>slug(r.name)));const out=new Map<string,string>();for(const entry of await readdir("staging/uapt-runs",{withFileTypes:true})){if(!entry.isDirectory())continue;try{const bundle=await json(path.join("staging/uapt-runs",entry.name,"artifacts.json"));for(const artifact of bundle.artifacts??[])if(artifact.artifactType==="source_candidate"&&artifact.verificationStatus==="verified"&&wanted.has(artifact.entitySlug)){const host=new URL(artifact.finalUrl??artifact.sourceUrl).hostname.toLowerCase().replace(/^www\./,"");const value=rootDomain(host);if(!out.has(artifact.entitySlug)||value.length<out.get(artifact.entitySlug)!.length)out.set(artifact.entitySlug,value)}}catch{}}return out}
async function persist(entries:Json[]){await writeFile(OUTPUT,`${JSON.stringify({schemaVersion:"uapt-ai-tools-search-trace-v1",runId:RUN,generatedAt:new Date().toISOString(),selection:"QS source rowNumber 501-600",entries},null,2)}\n`)}
async function keyFromConfig(){const cfg=await readFile("/Users/newvolume/.codex/config.toml","utf8");const k=cfg.match(/^\s*FIRECRAWL_API_KEY\s*=\s*[\"']?([^\s\"']+)/m)?.[1];if(!k)throw new Error("FIRECRAWL_API_KEY unavailable");return k}
async function json(file:string):Promise<Json>{return JSON.parse(await readFile(file,"utf8"))} function official(value:string,domain?:string){try{if(!domain)return false;const h=new URL(value).hostname.toLowerCase().replace(/^www\./,"");return h===domain||h.endsWith(`.${domain}`)}catch{return false}} function rootDomain(host:string){const special=["ac.uk","edu.au","ac.jp","edu.tw","ac.kr","edu.cn","ac.ae","edu.my"];for(const suffix of special)if(host===suffix||host.endsWith(`.${suffix}`))return host.split(".").slice(-(suffix.split(".").length+1)).join(".");return host.split(".").slice(-2).join(".")} function slug(value:string){return value.normalize("NFKD").replace(/\p{M}/gu,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").replace(/^the-/,"").replace(/-formerly.*$/,"")}
