import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type Json = Record<string, any>;
const RUN = "uapt-ai-tools-qs-501-600-20260718-009";
const TRACE = "staging/ai-tools/audits/qs-501-600-search-traces-20260718-009.json";
const RETRIES = "staging/ai-tools/audits/qs-501-600-search-trace-retries-20260718-009.json";
const OUTPUT = "staging/ai-tools/audits/qs-501-600-official-page-checks-20260718-009.json";
const SNAPSHOTS = `staging/ai-tools/audits/snapshots/${RUN}/direct-review`;
void main().catch((error) => { console.error(error); process.exitCode = 1; });
async function main() {
  const [trace,retries,key,prior] = await Promise.all([json(TRACE),json(RETRIES),apiKey(),existingChecks()]); const retryByKey=new Map(retries.retries.map((x:Json)=>[`${x.qsRow}\u0000${x.query}\u0000${x.queryLanguage}`,x])); const rows=trace.entries.map((entry:Json)=>({...entry,searchTrace:entry.searchTrace.map((q:Json)=>retryByKey.get(`${entry.qsRow}\u0000${q.query}\u0000${q.queryLanguage}`)??q)})); const checks:Json[]=prior; const completed=new Set(prior.map((check:Json)=>check.qsRow)); await mkdir(SNAPSHOTS,{recursive:true});
  const pending=rows.filter((row:Json)=>!completed.has(row.qsRow)); for(let i=0;i<pending.length;i+=8){const batch=await Promise.all(pending.slice(i,i+8).map((row:Json)=>crawlRow(key,row)));checks.push(...batch.flat());checks.sort((a,b)=>a.qsRow-b.qsRow||a.requestedUrl.localeCompare(b.requestedUrl));await writeFile(OUTPUT,`${JSON.stringify({schemaVersion:"uapt-ai-tools-official-page-checks-v1",runId:RUN,generatedAt:new Date().toISOString(),checks},null,2)}\n`);console.log(`Saved direct checks ${checks.length}; completed rows ${new Set(checks.map((check:Json)=>check.qsRow)).size}/100`)}
}
async function crawlRow(key:string,row:Json){const urls=[...new Set(row.searchTrace.flatMap((q:Json)=>q.candidateUrls??[]))].sort((a,b)=>score(b)-score(a)||a.localeCompare(b)).slice(0,6);return pool(urls,3,(url)=>scrape(key,row,url))}
async function scrape(key:string,row:Json,url:string){const fetchedAt=new Date().toISOString();try{const response=await fetch("https://api.firecrawl.dev/v2/scrape",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({url,formats:["markdown"],onlyMainContent:true}),signal:AbortSignal.timeout(45_000)});const data=await response.json();const result=data?.data??{};const markdown=String(result.markdown??"");const finalUrl=result.metadata?.sourceURL??result.metadata?.url??url;const status=result.metadata?.statusCode??response.status;const sourceLanguage=result.metadata?.language??"und";const title=result.metadata?.title??"Official university page";const official=isOfficial(finalUrl,row.officialDomain);const bytes=Buffer.from(markdown,"utf8");const snapshotPath=path.join(SNAPSHOTS,`${String(row.qsRow).padStart(3,"0")}-${slug(new URL(finalUrl).hostname+new URL(finalUrl).pathname)}-${hash(url).slice(0,10)}.md`);if(response.ok&&official&&markdown)await writeFile(snapshotPath,bytes);const text=normalize(markdown);const signals=signalTerms(text);return{qsRow:row.qsRow,universityName:row.universityName,officialDomain:row.officialDomain,requestedUrl:url,finalUrl,fetchedAt,provider:"firecrawl_scrape_v2",fetchStatus:response.ok&&markdown?"ok":"error",httpStatus:status,official,sourceTitle:title,sourceLanguage,snapshotPath:response.ok&&official&&markdown?snapshotPath:null,snapshotHash:response.ok&&official&&markdown?hash(bytes):null,relevantAiSurface:signals.products.length>0||signals.aiGeneric,potentialInstitutionalAccess:signals.products.length>0&&signals.access,signalTerms:signals.products,...(response.ok&&markdown?{}:{error:String(data?.error??`HTTP ${response.status}`)})};}catch(error){return{qsRow:row.qsRow,universityName:row.universityName,officialDomain:row.officialDomain,requestedUrl:url,finalUrl:url,fetchedAt,provider:"firecrawl_scrape_v2",fetchStatus:"error",httpStatus:null,official:isOfficial(url,row.officialDomain),sourceTitle:null,sourceLanguage:"und",snapshotPath:null,snapshotHash:null,relevantAiSurface:false,potentialInstitutionalAccess:false,signalTerms:[],error:String(error)}}}
function signalTerms(text:string){const products=[...text.matchAll(/\b(?:chatgpt|(?:microsoft )?copilot(?: chat)?|microsoft 365 copilot|github copilot|(?:google )?gemini|notebook\s*lm|(?:anthropic )?claude|perplexity|adobe (?:express|firefly)|cometai)\b/giu)].map(x=>x[0]);return{products:[...new Set(products)].slice(0,10),aiGeneric:/(?:generative ai|artificial intelligence|生成式AI|人工智能|인공지능|intelligence artificielle|künstliche intelligenz|inteligencia artificial)/iu.test(text),access:/(?:licensed?|procured|purchased|enterprise|institutional (?:account|access|licen[cs]|subscription)|university (?:account|credentials|provided)|available to.{0,80}(?:students?|staff|faculty)|provided to.{0,80}(?:students?|staff|faculty)|sign in.{0,80}(?:university|account)|single sign.on|\bsso\b|campus.?wide|学校账号|校园账号|学内アカウント|대학 계정|universitätskonto|compte universitaire|cuenta universitaria)/iu.test(text)}}
function score(url:string){const s=decodeURIComponent(url).toLowerCase();let v=0;if(/chatgpt|copilot|gemini|notebook|claude|perplexity|firefly|adobe-express|generative|artificial.intelligence|\/ai(?:\/|$)|ai-tools|ai-studio|cometai/.test(s))v+=60;if(/\/(?:it|oit|ict|digital|service|services|support|software|tools|platform|library|learning|teaching|research|procurement)/.test(s))v+=15;if(/\.pdf(?:$|\?)/.test(s))v-=30;if(/(?:repository|bitstream|publication|thesis|journal|proceedings|catalog|course|programme|program)/.test(s))v-=25;return v}
async function existingChecks():Promise<Json[]>{try{return (await json(OUTPUT)).checks??[]}catch{return[]}}async function json(file:string):Promise<Json>{return JSON.parse(await readFile(file,"utf8"))}async function apiKey(){const cfg=await readFile("/Users/newvolume/.codex/config.toml","utf8");const k=cfg.match(/^\s*FIRECRAWL_API_KEY\s*=\s*[\"']?([^\s\"']+)/m)?.[1];if(!k)throw new Error("FIRECRAWL_API_KEY unavailable");return k}function isOfficial(value:string,domain?:string){try{if(!domain)return false;const h=new URL(value).hostname.toLowerCase().replace(/^www\./,"");return h===domain||h.endsWith(`.${domain}`)}catch{return false}}function normalize(v:string){return v.normalize("NFKC").replace(/[\u00a0\s]+/g," ").trim()}function slug(v:string){return v.normalize("NFKD").replace(/\p{M}/gu,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100)||"page"}function hash(v:string|Uint8Array){return createHash("sha256").update(v).digest("hex")}async function pool<T,R>(items:T[],n:number,fn:(item:T)=>Promise<R>){const out:R[]=[];let next=0;await Promise.all(Array.from({length:Math.min(n,items.length)},async()=>{while(next<items.length){const i=next++;out[i]=await fn(items[i]);}}));return out}
