import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";

type Json=Record<string,any>;
const OUTPUT="staging/ai-tools/audits/qs-701-857-independent-qa-20260719-012.json";
const normalize=(value:string)=>value.normalize("NFKC").replace(/[\u00a0\s]+/g," ").trim();
const visible=(value:string)=>normalize(value.replace(/[*_#`|]/g," ").replace(/\[([^\]]+)\]\([^\)]+\)/g,"$1"));
const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");

async function main(){
  const [extension,ledger,review,ranking]=await Promise.all([json("staging/ai-tools/release-candidates/uapt-ai-tools-qs-701-857-20260719-012/tool_records.json"),json("staging/ai-tools/audits/qs-701-857-ai-tools-audit-ledger-20260719-012.json"),json("staging/ai-tools/audits/qs-701-857-high-risk-semantic-review-20260719-012.json"),json("data/rankings/qs-world-university-rankings-2026-top-1000.json")]);
  const failures:string[]=[];const positiveChecks:Json[]=[];
  for(const record of extension.records){for(const evidence of record.evidence??[]){const bytes=await readFile(evidence.snapshotPath);const text=visible(bytes.toString("utf8"));if(sha(bytes)!==evidence.snapshotHash)failures.push(`snapshot hash mismatch ${recordId(record)}`);if(!text.includes(normalize(evidence.evidenceSnippetOriginal)))failures.push(`non-contiguous quote ${recordId(record)} ${evidence.sourceUrl}`);const entry=ledger.entries.find((item:Json)=>item.qsRow===record.qsRow);if(!entry||!official(evidence.sourceUrl,entry.officialDomain))failures.push(`non-official evidence domain ${recordId(record)} ${evidence.sourceUrl}`);}positiveChecks.push({recordId:recordId(record),qsRow:record.qsRow,outcome:"confirmed_positive",evidenceCount:record.evidence.length});}
  const decisionKeys=new Set(review.decisions.map((item:Json)=>`${item.qsRow}|${canonical(item.sourceUrl)}`));const blockedEntries=ledger.entries.filter((entry:Json)=>entry.auditStatus==="blocked");
  for(const entry of ledger.entries){if(entry.verifiedZero!==false)failures.push(`verified zero forbidden at ${entry.qsRow}`);if(entry.requiredSearchMatrix.length!==5)failures.push(`search matrix not five at ${entry.qsRow}`);if(entry.auditStatus==="blocked"&&!entry.blockingReason)failures.push(`missing blocked boundary ${entry.qsRow}`);for(const page of entry.directOfficialPageChecks.filter((page:Json)=>page.fetchStatus==="ok"&&(page.semanticSignals?.productTerms?.length??0)>0&&(page.semanticSignals?.accessTerms?.length??0)>0)){if(!decisionKeys.has(`${entry.qsRow}|${canonical(page.finalUrl)}`))failures.push(`unreviewed semantic surface ${entry.qsRow} ${page.finalUrl}`);}}
  const blockedSample=spread(blockedEntries,55);const blockedChecks=blockedSample.map((entry:Json)=>({qsRow:entry.qsRow,universityName:entry.universityName,countryOrRegion:entry.countryOrRegion,localLanguage:entry.localLanguage,queryCount:entry.searchTrace.length,successfulQueries:entry.searchTrace.filter((item:Json)=>item.status!=="error").length,semanticSurfaces:entry.directOfficialPageChecks.filter((page:Json)=>(page.semanticSignals?.productTerms?.length??0)>0&&(page.semanticSignals?.accessTerms?.length??0)>0).length,outcome:"blocked_null_boundary_confirmed"}));
  for(const check of blockedChecks)if(check.successfulQueries===0)failures.push(`blocked sample lacks successful query ${check.qsRow}`);
  const uniqueSources=[...new Map(extension.records.flatMap((record:Json)=>record.evidence.map((evidence:Json)=>[`${record.qsRow}|${evidence.sourceUrl}`,{qsRow:record.qsRow,url:evidence.sourceUrl}])).map((value:any)=>value as [string,Json])).values()];
  const liveChecks=await pool(uniqueSources,8,liveCheck);const liveSuccess=liveChecks.filter(item=>item.outcome==="reachable_official_source");if(liveSuccess.length<25)failures.push(`only ${liveSuccess.length} independent live sources reachable`);
  const countryByRow=new Map(ranking.universities.map((row:Json)=>[row.rowNumber,row.countryOrRegion]));const regionGroups=[...new Set(extension.records.map((record:Json)=>region(String(countryByRow.get(record.qsRow)??"Unknown"))))];if(regionGroups.length<6)failures.push(`only ${regionGroups.length} region groups`);
  const manualBoundaryCases=[
    {qsRow:702,outcome:"excluded_research_or_company_access",rationale:"ZHAW sources discuss external SwissGPT company access and research, not a current ZHAW community entitlement."},
    {qsRow:705,outcome:"excluded_expired_program",rationale:"Auburn's separate Microsoft 365 Copilot funding evidence ended in September 2025; current Firefly and base Copilot evidence is retained."},
    {qsRow:731,outcome:"excluded_vendor_student_promotion",rationale:"The one-year Gemini student promotion is a Google offer verified by student email, not a KMUTT institutional licence; library AI Corner access is retained."},
    {qsRow:733,outcome:"excluded_generic_products",rationale:"Michigan Tech papers and generic tool lists were excluded; only the current IT page's institutional Gemini access was retained."},
    {qsRow:753,outcome:"excluded_personal_account_offer",rationale:"The Google AI Pro student offer is tied to personal Gmail accounts and explicitly not U of I accounts; U of I Copilot, Claude, and Zoom evidence is retained."},
    {qsRow:782,outcome:"excluded_broken_placeholder",rationale:"The UniUd ChatGPT Edu URL renders a zero-result placeholder and does not establish access."},
    {qsRow:816,outcome:"excluded_policy_mentions",rationale:"Canterbury guidance discusses many public tools but does not establish a university account, licence, procurement route, or operated service."},
    {qsRow:851,outcome:"excluded_generic_catalog",rationale:"The UWB AI catalog is generic; only Copilot and Gemini tied to university Office 365 and Workspace licences were retained."}
  ];
  const report={schemaVersion:"uapt-ai-tools-independent-qa-v1",runId:"uapt-ai-tools-qs-701-857-20260719-012",generatedAt:new Date().toISOString(),scope:{positiveRecords:extension.records.length,positiveSources:uniqueSources.length,blockedSamples:blockedChecks.length,regionGroups,method:"Independent pass over every evidence hash and contiguous quote; direct live re-fetch of every selected source; spread sample of blocked rows; and explicit reverse review of high-risk boundaries."},summary:{confirmed_positive:failures.length?positiveChecks.length-failures.length:positiveChecks.length,false_positive:failures.filter(item=>item.includes("positive")).length,false_negative:failures.filter(item=>item.includes("unreviewed semantic surface")).length,inconclusive:failures.length,live_sources_reachable:liveSuccess.length,live_sources_checked:liveChecks.length,blocked_rows_checked:blockedChecks.length},positiveChecks,blockedChecks,liveChecks,manualBoundaryCases,failures};
  await writeFile(OUTPUT,`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify(report.summary,null,2));if(failures.length)throw new Error(failures.join("\n"));
}

async function liveCheck(source:Json){try{const response=await fetch(source.url,{redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; UAPT-QA/1.0; +https://eduaipolicy.org)"},signal:AbortSignal.timeout(20_000)});const type=response.headers.get("content-type")??"";let text="";if(response.ok&&/text\/(?:html|plain)/i.test(type))text=html(await response.text());else if(response.ok&&/application\/pdf/i.test(type)){const converted=spawnSync("pdftotext",["-","-"],{input:Buffer.from(await response.arrayBuffer()),maxBuffer:25_000_000});if(converted.status===0)text=converted.stdout.toString("utf8");}return{...source,finalUrl:response.url,status:response.status,contentType:type,outcome:response.ok&&text.length>100&&sameSite(source.url,response.url)?"reachable_official_source":"live_fetch_boundary",contentLength:text.length};}catch(error){return{...source,outcome:"live_fetch_boundary",error:String(error)};}}
function spread(entries:Json[],count:number){if(entries.length<=count)return entries;const output:Json[]=[];for(let index=0;index<count;index++)output.push(entries[Math.floor(index*(entries.length-1)/(count-1))]);return[...new Map(output.map(item=>[item.qsRow,item])).values()];}
function region(country:string){if(["United States","Canada"].includes(country))return"North America";if(["United Kingdom","Ireland"].includes(country))return"UK and Ireland";if(["China (Mainland)","Taiwan","Japan","South Korea"].includes(country))return"East Asia";if(["India","Pakistan","Bangladesh","Sri Lanka"].includes(country))return"South Asia";if(["Chile","Argentina","Ecuador","Mexico","Venezuela","Brazil","Costa Rica","Panama","Peru"].includes(country))return"Latin America";if(["Oman","Saudi Arabia","Jordan","Lebanon","Egypt","Tunisia","Iran","Türkiye","Syria","Libya"].includes(country))return"Middle East and North Africa";if(["Australia"].includes(country))return"Oceania";if(["Thailand","Malaysia","Indonesia","Vietnam"].includes(country))return"Southeast Asia";return"Continental Europe and other";}
function official(url:string,domain:string){try{const host=new URL(url).hostname.toLowerCase().replace(/^www\./,"");return host===domain||host.endsWith(`.${domain}`);}catch{return false;}}
function sameSite(a:string,b:string){try{const x=new URL(a).hostname.replace(/^www\./,""),y=new URL(b).hostname.replace(/^www\./,"");return x===y||x.endsWith(`.${y}`)||y.endsWith(`.${x}`);}catch{return false;}}
function canonical(value:string){try{const url=new URL(value);url.hash="";return`${url.hostname.toLowerCase().replace(/^www\./,"")}${url.pathname.replace(/\/$/,"")}${url.search}`;}catch{return value;}}
function html(value:string){return value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim();}
function recordId(record:Json){return`${record.universitySlug}:${record.tool}:${record.rawToolName}`;}
async function json(file:string):Promise<Json>{return JSON.parse(await readFile(file,"utf8"));}
async function pool<T,R>(items:T[],concurrency:number,task:(item:T)=>Promise<R>){const output:R[]=[];let next=0;await Promise.all(Array.from({length:Math.min(concurrency,items.length)},async()=>{while(next<items.length){const index=next++;output[index]=await task(items[index]);}}));return output;}
void main().catch(error=>{console.error(error);process.exitCode=1;});
