import { readFile, writeFile } from "node:fs/promises";

type Json = Record<string, any>;
const INPUT = "staging/ai-tools/audits/qs-501-600-search-traces-20260718-009.json";
const OUTPUT = "staging/ai-tools/audits/qs-501-600-search-trace-retries-20260718-009.json";
void main().catch((error) => { console.error(error); process.exitCode = 1; });
async function main() {
  const [input,key] = await Promise.all([json(INPUT), apiKey()]);
  const failed = input.entries.flatMap((entry: Json) => entry.searchTrace.filter((trace: Json) => trace.fetchStatus === "error").map((trace: Json) => ({qsRow:entry.qsRow,officialDomain:entry.officialDomain,...trace})));
  const existing = await existingRetries(); const done = new Set(existing.map((x: Json) => `${x.qsRow}\u0000${x.query}\u0000${x.queryLanguage}`)); const pending = failed.filter((x: Json) => !done.has(`${x.qsRow}\u0000${x.query}\u0000${x.queryLanguage}`));
  console.log(`Retrying ${pending.length} of ${failed.length} failed Firecrawl searches at concurrency 2.`);
  for (let i=0;i<pending.length;i+=20) { const batch = await pool(pending.slice(i,i+20),2,(item)=>retry(key,item)); existing.push(...batch); await writeFile(OUTPUT,`${JSON.stringify({schemaVersion:"uapt-ai-tools-search-trace-retries-v1",runId:"uapt-ai-tools-qs-501-600-20260718-009",generatedAt:new Date().toISOString(),retries:existing},null,2)}\n`); console.log(`Saved retries ${existing.length}/${failed.length}`); }
}
async function retry(key:string,item:Json){const retriedAt=new Date().toISOString();try{const response=await fetch("https://api.firecrawl.dev/v2/search",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({query:item.query,limit:8,sources:["web"],timeout:30000})});const data=await response.json();const values=data?.data?.web??data?.data??[];const urls=[...new Set(values.map((x:Json)=>x.url).filter((url:unknown):url is string=>typeof url==="string"&&official(url,item.officialDomain)))];return {qsRow:item.qsRow,query:item.query,queryLanguage:item.queryLanguage,provider:"firecrawl_search_v2",retriedAt,priorFailure:item.error??null,firecrawlSearchId:data?.id??null,creditsUsed:data?.creditsUsed??null,fetchStatus:response.ok?(urls.length?"ok":"empty"):"error",candidateUrls:urls,filteredIrrelevantCount:values.length-urls.length,filteringConclusion:urls.length?"Official-domain candidates retained after retry.":response.ok?"HTTP 200 with no official-domain candidate URL; recorded as empty.":`Firecrawl HTTP ${response.status}`,...(response.ok?{}:{error:String(data?.error??`HTTP ${response.status}`)})};}catch(error){return{qsRow:item.qsRow,query:item.query,queryLanguage:item.queryLanguage,provider:"firecrawl_search_v2",retriedAt,priorFailure:item.error??null,fetchStatus:"error",candidateUrls:[],filteredIrrelevantCount:0,filteringConclusion:"Retry failed.",error:String(error)}}}
async function existingRetries():Promise<Json[]>{try{return (await json(OUTPUT)).retries??[]}catch{return[]}} async function json(file:string):Promise<Json>{return JSON.parse(await readFile(file,"utf8"))} async function apiKey(){const cfg=await readFile("/Users/newvolume/.codex/config.toml","utf8");const k=cfg.match(/^\s*FIRECRAWL_API_KEY\s*=\s*[\"']?([^\s\"']+)/m)?.[1];if(!k)throw new Error("FIRECRAWL_API_KEY unavailable");return k} function official(value:string,domain?:string){try{if(!domain)return false;const h=new URL(value).hostname.toLowerCase().replace(/^www\./,"");return h===domain||h.endsWith(`.${domain}`)}catch{return false}} async function pool<T,R>(items:T[],n:number,fn:(item:T)=>Promise<R>){const out:R[]=[];let next=0;await Promise.all(Array.from({length:Math.min(n,items.length)},async()=>{while(next<items.length){const i=next++;out[i]=await fn(items[i]);}}));return out}
