import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  getCurrentPublicReleaseManifest,
  getStagedPublicSummaries
} from "../apps/web/lib/staged-public-data";

// Regenerates the release block inside README.md "Current Status" from the
// live merge of data/public-releases/current.json, replacing the content
// between the release-status markers. Run after each release promotion so the
// README can no longer drift from the published dataset.

const START = "<!-- release-status:start -->";
const END = "<!-- release-status:end -->";

async function main() {
  const manifest = await getCurrentPublicReleaseManifest();
  if (!manifest) throw new Error("No current public release manifest found.");
  const summaries = await getStagedPublicSummaries();

  let claims = 0;
  let evidence = 0;
  let sources = 0;
  const claimStates = new Map<string, number>();
  const entityStates = new Map<string, number>();
  const languages = new Set<string>();

  for (const summary of summaries) {
    sources += summary.officialSources.length;
    entityStates.set(
      summary.reviewState,
      (entityStates.get(summary.reviewState) ?? 0) + 1
    );
    for (const claim of summary.claims) {
      claims += 1;
      evidence += claim.evidence.length;
      claimStates.set(
        claim.reviewState,
        (claimStates.get(claim.reviewState) ?? 0) + 1
      );
      for (const item of claim.evidence) {
        if (item.sourceLanguage) languages.add(item.sourceLanguage);
      }
    }
  }

  const formatStates = (states: Map<string, number>) =>
    [...states.entries()]
      .sort((left, right) => right[1] - left[1])
      .map(([state, count]) => `${count} \`${state}\``)
      .join(", ");

  const block = [
    START,
    "",
    `- Release: \`${manifest.releaseId}\` (published ${manifest.publishedAt.slice(0, 10)})`,
    `- Universities: ${summaries.length}`,
    `- Claims: ${claims}`,
    `- Evidence records: ${evidence}`,
    `- Official source attributions: ${sources}`,
    `- Entity review states: ${formatStates(entityStates)}`,
    `- Claim review states: ${formatStates(claimStates)}`,
    `- Source languages represented: ${languages.size} language tags across the evidence set`,
    "",
    `Generated by \`pnpm readme:update-status\` from the release manifest and staged merge.`,
    "",
    END
  ].join("\n");

  const readmePath = path.join(process.cwd(), "README.md");
  const readme = await readFile(readmePath, "utf8");
  const startIndex = readme.indexOf(START);
  const endIndex = readme.indexOf(END);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error(
      `README.md must contain the ${START} and ${END} markers in order.`
    );
  }

  const updated =
    readme.slice(0, startIndex) + block + readme.slice(endIndex + END.length);
  await writeFile(readmePath, updated, "utf8");
  console.log(
    `README release block updated: ${manifest.releaseId}, ${summaries.length} universities, ${claims} claims.`
  );
}

void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
