import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";
import { openClawArtifactBundleSchema } from "@uapt/shared";
type Json = Record<string, any>;
const read = async (path:string) => JSON.parse(await readFile(path,"utf8"));
const sha = (s:string|Buffer) => createHash("sha256").update(s).digest("hex");
const normalized = (s:string) => s.normalize("NFKC").replace(/[\u00a0\s]+/g," ").trim();
const visible = (s:string) => normalized(s.replace(/[*_#`|]/g," ").replace(/\[([^\]]+)\]\([^\)]+\)/g,"$1"));
async function main(){
 const current=await readFile("data/public-releases/current.json","utf8"); const currentHash=sha(current); const currentManifest=JSON.parse(current); const qa=await read("staging/ai-tools/audits/qs-501-600-independent-qa-20260718-009.json");
 const baselineText=await readFile("staging/ai-tools/release-candidates/uapt-ai-tools-qs-top-500-20260718-008/tool_records.json","utf8"); const baseline=JSON.parse(baselineText); const ext=await read("staging/ai-tools/release-candidates/uapt-ai-tools-qs-501-600-20260718-009/tool_records.json"); const top=await read("staging/ai-tools/release-candidates/uapt-ai-tools-qs-top-600-20260718-009/tool_records.json"); const ledger=await read("staging/ai-tools/audits/qs-501-600-ai-tools-audit-ledger-20260718-009.json"); const review=await read("staging/ai-tools/audits/qs-501-600-high-risk-semantic-review-20260718-009.json"); const bundle=await read("staging/uapt-runs/uapt-ai-tools-qs-top-600-20260718-009/artifacts.json"); const candidate=await read("data/public-releases/candidates/public-release-20260718-009.json"); const manifest=await read("staging/ai-tools/release-candidates/uapt-ai-tools-qs-top-600-20260718-009/candidate-manifest.json");
 assert.equal(sha(baselineText),"2086267d34502b5441c5f8b08f8578498850b55783f15c1a31ed28a37bf44f3f"); assert.equal(manifest.baseline.sha256,sha(baselineText)); assert.equal(top.records.length,baseline.records.length+ext.records.length); for(let i=0;i<baseline.records.length;i++) assert.deepEqual(top.records[i],baseline.records[i]);
 assert.equal(candidate.previousReleaseId,"public-release-20260718-008"); if(candidate.candidateOnly===true){assert.equal(currentManifest.releaseId,"public-release-20260718-008");}else{assert.equal(currentManifest.releaseId,candidate.releaseId);assert.deepEqual(currentManifest,candidate);}
 const keys=top.records.map((r:Json)=>`${r.universitySlug}:${r.tool}:${r.rawToolName}`); assert.equal(new Set(keys).size,keys.length); assert.equal(ledger.entries.length,100); assert.deepEqual(ledger.entries.map((e:Json)=>e.qsRow),Array.from({length:100},(_,i)=>i+501)); for(const entry of ledger.entries){assert.equal(entry.requiredSearchMatrix.length,8);assert.ok(entry.searchTrace.length>=8);assert.equal(entry.verifiedZero,false);if(entry.auditStatus==="blocked")assert.ok(entry.blockingReason);} for(const d of review.decisions){assert.ok(d.reviewedSourceUrls.length);assert.ok(d.semanticDecision);assert.ok(d.reviewerOrigin);assert.ok(d.reviewedAt);} assert.equal(qa.summary.confirmed_positive,ext.records.length); assert.equal(qa.summary.false_positive,0); assert.equal(qa.summary.false_negative,0); assert.equal(qa.summary.inconclusive,0); assert.ok(qa.scope.blockedSamples>=40); assert.ok(qa.scope.regionGroups.length>=8);
 for(const r of ext.records)for(const e of r.evidence){const bytes=await readFile(e.snapshotPath);assert.equal(sha(bytes),e.snapshotHash);assert.ok(visible(bytes.toString("utf8")).includes(normalized(e.evidenceSnippetOriginal)));}
 openClawArtifactBundleSchema.parse(bundle); const counts:Record<string,number>={};for(const a of bundle.artifacts)counts[a.artifactType]=(counts[a.artifactType]||0)+1; for(const type of ["crawl_plan","source_discovery_trace","source_candidate","fetch_attempt","source_snapshot","evidence_candidate","claim_candidate","review_decision","report_draft"])assert.ok(counts[type]>0,`missing ${type}`);assert.equal(counts.claim_candidate,top.records.length);assert.equal(counts.review_decision,top.records.length);assert.ok(candidate.includeStagedArtifactDirectories.includes("staging/uapt-runs/uapt-ai-tools-qs-top-600-20260718-009")); console.log(JSON.stringify({ok:true,currentHash,releaseState:candidate.candidateOnly===true?"candidate":"promoted",baselineRecords:baseline.records.length,extensionRecords:ext.records.length,top600Records:top.records.length,artifactCounts:counts},null,2));
}
main().catch(error=>{console.error(error);process.exit(1)});
