import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { aiTools, openClawArtifactBundleSchema } from "@uapt/shared";
type Json=Record<string,any>;
const read=async(file:string)=>JSON.parse(await readFile(file,"utf8"));
const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const normalized=(value:string)=>value.normalize("NFKC").replace(/[\u00a0\s]+/g," ").trim();
const visible=(value:string)=>normalized(value.replace(/[*_#`|]/g," ").replace(/\[([^\]]+)\]\([^\)]+\)/g,"$1"));
async function main(){
 const activeText=await readFile("data/public-releases/current.json","utf8");const active=JSON.parse(activeText);const currentText=active.releaseId==="public-release-20260719-011"?await readFile("data/public-releases/history/public-release-20260718-009.json","utf8"):activeText;const current=JSON.parse(currentText);const currentHash=sha(currentText);
 const baselineText=await readFile("staging/ai-tools/release-candidates/uapt-ai-tools-qs-top-600-20260718-009/tool_records.json","utf8");const baseline=JSON.parse(baselineText);
 const [ext,top,ledger,review,qa,bundle,candidate,manifest,discovery]=await Promise.all([read("staging/ai-tools/release-candidates/uapt-ai-tools-qs-601-700-20260719-011/tool_records.json"),read("staging/ai-tools/release-candidates/uapt-ai-tools-qs-top-700-20260719-011/tool_records.json"),read("staging/ai-tools/audits/qs-601-700-ai-tools-audit-ledger-20260719-011.json"),read("staging/ai-tools/audits/qs-601-700-high-risk-semantic-review-20260719-011.json"),read("staging/ai-tools/audits/qs-601-700-independent-qa-20260719-011.json"),read("staging/uapt-runs/uapt-ai-tools-qs-top-700-20260719-011/artifacts.json"),read("data/public-releases/candidates/public-release-20260719-011.json"),read("staging/ai-tools/release-candidates/uapt-ai-tools-qs-top-700-20260719-011/candidate-manifest.json"),read("staging/ai-tools/audits/qs-601-700-discovery-20260719-011.json")]);
 assert.equal(current.releaseId,"public-release-20260718-009");assert.equal(candidate.releaseId,"public-release-20260719-011");assert.equal(candidate.previousReleaseId,current.releaseId);assert.equal(candidate.candidateOnly,true);assert.equal(sha(baselineText),"999035d954e75cadfd06fb263010f79ed0369823e4f7664582baa2cb983c5d1b");assert.equal(manifest.baseline.sha256,sha(baselineText));assert.equal(manifest.output.sha256,sha(await readFile(manifest.output.path,"utf8")));
 assert.equal(ext.records.length,71);assert.equal(new Set(ext.records.map((record:Json)=>record.universitySlug)).size,28);assert.equal(top.records.length,baseline.records.length+ext.records.length);for(let index=0;index<baseline.records.length;index++)assert.deepEqual(top.records[index],baseline.records[index]);
 const ids=top.records.map(recordId);assert.equal(new Set(ids).size,ids.length);const allowed=new Set(aiTools);for(const record of ext.records){assert.ok(record.qsRow>=601&&record.qsRow<=700);assert.ok(allowed.has(record.tool),`unknown tool ${record.tool}`);assert.ok(record.institutionalRelationship);assert.ok(record.accessAudience);assert.ok(record.accessStatus);for(const evidence of record.evidence){const bytes=await readFile(evidence.snapshotPath);assert.equal(sha(bytes),evidence.snapshotHash);assert.ok(visible(bytes.toString("utf8")).includes(normalized(evidence.evidenceSnippetOriginal)),`quote mismatch ${recordId(record)}`);}}
	 assert.equal(discovery.rows.length,100);assert.equal(ledger.entries.length,100);assert.deepEqual(ledger.entries.map((entry:Json)=>entry.qsRow),Array.from({length:100},(_,index)=>index+601));assert.equal(ledger.summary.searchTraces,1108);assert.equal(ledger.summary.searchErrors,0);assert.equal(ledger.summary.verifiedZero,0);assert.equal(ledger.summary.undLocalLanguageRows,0);for(const entry of ledger.entries){assert.equal(entry.verifiedZero,false);assert.ok(entry.searchTrace.length>=8);assert.equal(entry.searchBoundary.errors,entry.searchTrace.filter((item:Json)=>item.status==="error").length);if(entry.auditStatus==="blocked")assert.ok(entry.blockingReason);}
	 assert.equal(review.decisions.length,241);for(const decision of review.decisions){assert.ok(decision.sourceUrl);assert.ok(decision.semanticDecision);assert.ok(decision.rationale);assert.ok(decision.reviewerOrigin);assert.ok(decision.reviewedAt);}assert.equal(qa.summary.confirmed_positive,71);assert.equal(qa.summary.false_positive,0);assert.equal(qa.summary.false_negative,0);assert.equal(qa.summary.inconclusive,0);assert.ok(qa.summary.live_sources_reachable>=20);assert.ok(qa.scope.blockedSamples>=40);assert.ok(qa.scope.regionGroups.length>=6);
 openClawArtifactBundleSchema.parse(bundle);const counts:Record<string,number>={};for(const artifact of bundle.artifacts)counts[artifact.artifactType]=(counts[artifact.artifactType]??0)+1;for(const type of ["crawl_plan","source_discovery_trace","source_candidate","fetch_attempt","source_snapshot","evidence_candidate","claim_candidate","review_decision","report_draft"])assert.ok(counts[type]>0,`missing ${type}`);assert.equal(counts.claim_candidate,top.records.length);assert.equal(counts.review_decision,top.records.length);assert.ok(candidate.includeStagedArtifactDirectories.includes("staging/uapt-runs/uapt-ai-tools-qs-top-700-20260719-011"));
 console.log(JSON.stringify({ok:true,currentHash,baselineRecords:baseline.records.length,extensionRecords:ext.records.length,topRecords:top.records.length,ledgerRows:ledger.entries.length,reviewedSurfaces:review.decisions.length,qa:qa.summary,artifactCounts:counts},null,2));
}
function recordId(record:Json){return`${record.universitySlug}:${record.tool}:${record.rawToolName}`;}
void main().catch(error=>{console.error(error);process.exitCode=1;});
